version: '3.8'

services:
  emqx:
    image: emqx/emqx:5.0.0
    container_name: emqx
    ports:
      - "1883:1883"    # MQTT端口
      - "8083:8083"    # MQTT over WebSocket端口
      - "8084:8084"    # MQTT over SSL端口
      - "8883:8883"    # MQTT over SSL端口
      - "18083:18083"  # Dashboard端口
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=127.0.0.1
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@127.0.0.1
      - EMQX_DASHBOARD__DEFAULT_USERNAME=admin
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public
      - EMQX_LISTENERS__TCP__DEFAULT__BIND=0.0.0.0:1883
      - EMQX_LISTENERS__WS__DEFAULT__BIND=0.0.0.0:8083
      - EMQX_LISTENERS__SSL__DEFAULT__BIND=0.0.0.0:8883
      - EMQX_LISTENERS__WSS__DEFAULT__BIND=0.0.0.0:8084
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
      - ./emqx.conf:/opt/emqx/etc/emqx.conf
    networks:
      - iot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=iot-org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - iot-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - iot-network
    restart: unless-stopped
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:1.27
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - iot-network
    restart: unless-stopped
    depends_on:
      - influxdb

  mqtt-simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    container_name: mqtt-simulator
    environment:
      - MQTT_BROKER=emqx
      - MQTT_PORT=1883
      - DEVICE_COUNT=10
      - MESSAGE_INTERVAL=5
    networks:
      - iot-network
    restart: unless-stopped
    depends_on:
      - emqx

  mqtt-subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    container_name: mqtt-subscriber
    environment:
      - MQTT_BROKER=emqx
      - MQTT_PORT=1883
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=iot-org
      - INFLUXDB_BUCKET=iot-data
    networks:
      - iot-network
    restart: unless-stopped
    depends_on:
      - emqx
      - influxdb

volumes:
  emqx_data:
    driver: local
  emqx_log:
    driver: local
  influxdb_data:
    driver: local
  grafana_data:
    driver: local

networks:
  iot-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
