groups:
  - name: demo-api-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx error rate"
          runbook: "docs/runbooks/demo-api-high-error-rate.md"
