name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --all-features
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Security Audit
        run: cargo audit
      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:latest . 