stages:
  - build
  - test
  - lint
  - docker

variables:
  RUST_BACKTRACE: 1

build:
  stage: build
  image: rust:1.70
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/

test:
  stage: test
  image: rust:1.70
  script:
    - cargo test --all-features

lint:
  stage: lint
  image: rust:1.70
  script:
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo audit

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main 