# Formal Framework 自动化工具链配置文件

# 内容扫描配置
content_scanner:
  required_files: 
    - "theory.md"
    - "dsl-draft.md"
  quality_threshold: 0.7
  scan_patterns: 
    - "*.md"
  exclude_patterns:
    - "**/temp/**"
    - "**/draft/**"
    - "**/.git/**"
    - "**/node_modules/**"
  min_file_size: 100
  required_sections:
    - "概念定义"
    - "理论基础"
    - "应用案例"
    - "最佳实践"

# 质量评估配置
quality_assessor:
  weights:
    completeness: 0.3
    consistency: 0.3
    readability: 0.4
  thresholds:
    warning: 0.6
    error: 0.4
  quality_indicators:
    min_content_length: 500
    min_code_blocks: 1
    min_links: 2
    min_sections: 3

# AI辅助配置
ai_completer:
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.7
  enabled: false  # 默认禁用，需要API密钥

# 知识图谱配置
knowledge_graph:
  layout: "spring"
  node_size: 1000
  font_size: 8
  output_format: "png"
  include_weights: true

# 报告生成配置
report_generator:
  output_format: "markdown"
  include_charts: true
  include_statistics: true
  template_path: "templates/report_template.md"

# 项目特定配置
project:
  name: "Formal Framework"
  version: "1.0.0"
  description: "形式化建模知识库项目"
  maintainers:
    - "项目维护者"
  
# 目录结构配置
directories:
  docs: "docs/"
  tools: "tools/"
  reports: "reports/"
  config: "config/"
  templates: "templates/"

# 文件命名规范
naming_conventions:
  theory_files: "theory.md"
  dsl_files: "dsl-draft.md"
  readme_files: "README.md"
  index_files: "index.md"

# 质量检查规则
quality_rules:
  # 内容长度规则
  content_length:
    min_chars: 500
    max_chars: 10000
    warning_threshold: 1000
  
  # 章节结构规则
  sections:
    required:
      - "概念定义"
      - "理论基础"
    optional:
      - "应用案例"
      - "最佳实践"
      - "开源项目映射"
  
  # 代码示例规则
  code_examples:
    min_count: 1
    preferred_languages:
      - "python"
      - "yaml"
      - "json"
      - "bash"
  
  # 链接规则
  links:
    min_internal_links: 2
    min_external_links: 1
    prefer_relative_links: true

# 自动化流程配置
automation:
  # 扫描频率
  scan_frequency: "weekly"
  
  # 报告生成
  auto_generate_reports: true
  report_retention_days: 30
  
  # 通知配置
  notifications:
    enabled: false
    email: []
    webhook: ""
  
  # 集成配置
  integrations:
    github_actions: true
    gitlab_ci: false
    jenkins: false

# 高级配置
advanced:
  # 并行处理
  parallel_processing: true
  max_workers: 4
  
  # 缓存配置
  cache_enabled: true
  cache_ttl_hours: 24
  
  # 调试模式
  debug_mode: false
  verbose_logging: false 